### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by japaric** [japaric/criterion.rs#2]
_Subject to change without prior notice_

Functionality:
- [x] Classification of outliers
- [x] Draw bootstrap distribution of statistics (mean,median,SD,MAD)
- [x] Draw bootstrap distribution of the relative change of the {mean,median,slope}
- Check if the relative change of the (mean,median) is "significant"
  - [x] Add threshold noise (percentage) field to the `Criterion struct`
  - [x] If the _whole_ confidence interval is below _minus_ threshold noise,
    there has been a improvement
  - [x] If the _whole_ confidence interval is above _plus_ threshold noise,
    there has been a regression
  - [x] `fail!` if both the mean and median have regressed
- Benchmark external programs
  - [x] Decide on the interface that the external program must implement
    - for each line in stdin; niters = parse line; print ns_elapsed for niters
  - [x] Hack up an implementation
  - [x] Refactor/DRY the implementation
- Summarize a bench group
  - [x] Plot {mean,median,slope} vs input + error bars (ci)
    - [x] add error bars for confidence intervals
    - [x] automagically trigger log scale when appropriate
  - [ ] Draw a trendline
    - [ ] Show the formula of the trendline + R^2
    - [ ] Draw the confidence interval of the trendline
- [x] Implement `#[criterion]` with procedural macros
  - [ ] Try to replicate functionality of the `--bench` flag
  - [ ] Or hide the benchs as tests behind `[cfg(bench)]`
- [x] Use euler problems as a testing ground
- [ ] Document the analysis process
- [x] Collect sample with a different number of iterations on each measurement
  - Number of iterations follow an arithmetic progression
  - [x] Store iteration/total time pairs
- [x] Linear regression
- [x] Factor out statistics related code to a library

Directory hierarchy:

```
.criterion
`-- fib
    |-- 10
    |   |-- base
    |   |   |-- MAD.svg
    |   |   |-- SD.svg
    |   |   |-- estimates.json
    |   |   |-- mean.svg
    |   |   |-- median.svg
    |   |   |-- outliers.json
    |   |   |-- pdf.svg
    |   |   |-- regression.svg
    |   |   |-- sample.json
    |   |   `-- slope.svg
    |   |-- both
    |   |   |-- pdf.svg
    |   |   `-- regression.svg
    |   |-- change
    |   |   |-- estimates.json
    |   |   |-- mean.svg
    |   |   |-- median.svg
    |   |   `-- t-test.svg
    |   `-- new
    |       `-- (...)  # Same as `base`
    |-- {15,20,5}
    |   `-- (...)  # Same as `10`
    `-- summary
        |-- base
        |   |-- means.svg
        |   |-- medians.svg
        |   `-- slopes.svg
        `-- new
            `-- (...)  # Same as `base`
```

Plots/Data dumps:
- [x] `sample.json`: Iteration/total time pair stored as `u64`
- [x] `estimates.json`: Estimate of several statistics
- `pdf.svg`
  - [x] sample PDF
  - [x] sample points
  - [x] color points depending on their "outlierness"
  - [x] fence lines
- [x] `outliers.json`: Store outlier count/fences
- [x] `both/pdf.svg`: base and new PDF on the same graph
- [x] `both/regression.svg`: base and new linear regressions on the same graph
- `{base,new}/{mean,median,SD,MAD}.svg`
  - [x] PDF of the bootstrap distribution
  - [x] Colored CI area
  - [x] Point estimate
- `change/{mean,median}.svg`
  - [x] PDF of the bootstrap distribution
  - [x] Colored CI area
  - [x] Point estimate
  - [x] Colored threshold noise
- `summary/{base,new}/{mean,median}.svg`
  - [x] point estimates
  - [x] error bars (CI)
  - [ ] trend line + formula

Also, plots must have:
- [x] Title
- [x] X/Y labels
- [x] properly scaled X/Y axis
- [x] Legend (if necessary)

Wishlist:
- plots should use:
  - [x] "nice" colors
  - [x] "nice" line styles
  - [x] A "nice" font
- JSON files
  - [x] should be "pretty" encoded
